# Generated by Django 3.2.3 on 2021-12-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성시간')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
            ],
        ),
    ]
