# Generated by Django 3.2.3 on 2021-12-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(to='account.StockBroker'),
        ),
    ]
