# Generated by Django 3.2.3 on 2021-12-14 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account_info_list', to='account.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_user_info_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account_info', 'user')},
            },
        ),
    ]
