# Generated by Django 3.2.3 on 2021-12-14 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211214_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='is_get_app_push',
            field=models.BooleanField(default=True, verbose_name='app push수신 여부 체크'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_get_email',
            field=models.BooleanField(default=True, verbose_name='메일수신 여부 체크'),
        ),
        migrations.AlterField(
            model_name='member',
            name='is_get_sms',
            field=models.BooleanField(default=True, verbose_name='sms수신 여부 체크'),
        ),
        migrations.RenameModel(
            old_name='Account',
            new_name='Company',
        ),
        migrations.DeleteModel(
            name='MemberAccount',
        ),
        migrations.AddField(
            model_name='membercompany',
            name='company_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_account_info_list', to='account.company'),
        ),
        migrations.AddField(
            model_name='membercompany',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_member_info_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='membercompany',
            unique_together={('company_info', 'member')},
        ),
    ]
