# Generated by Django 3.2.3 on 2021-12-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='태그명')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='상호명')),
                ('location', models.TextField(blank=True, null=True, verbose_name='위치')),
                ('link', models.URLField(blank=True, null=True, verbose_name='링크')),
                ('category', models.CharField(choices=[('한식', 'ko'), ('중식', 'cn'), ('양식', 'en'), ('일식', 'jp'), ('기타', 'etc')], max_length=20)),
                ('menu', models.TextField(blank=True, null=True, verbose_name='메뉴')),
                ('menu_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='메뉴 이미지')),
                ('food_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='음식 이미지')),
                ('is_closed', models.BooleanField(default=False, verbose_name='폐점여부')),
                ('description', models.TextField(blank=True, null=True, verbose_name='기타')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('tags', models.ManyToManyField(to='store.Tag')),
            ],
        ),
    ]
