FROM python:3.8
MAINTAINER hsj2334@gmail.com

RUN apt-get update && apt-get install -y vim supervisor nginx net-tools
COPY requirements.txt srv/

WORKDIR /srv
RUN pip install --no-cache-dir -r requirements.txt
