# Generated by Django 3.2.3 on 2021-12-17 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AddField(
            model_name='review',
            name='with_who',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
