# Generated by Django 3.2.3 on 2021-12-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211214_1627'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ipo_info_list', to='account.company')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_company_info_list', to='stocks.ipo')),
            ],
        ),
    ]
