# Generated by Django 3.2.3 on 2021-12-15 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_accounts'),
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPOStockBroker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_stock_broker_info_list', to='stocks.ipo')),
                ('stock_broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_broker_ipo_info_list', to='account.stockbroker')),
            ],
        ),
    ]
