# Generated by Django 3.2.3 on 2021-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='detail_link',
            field=models.URLField(blank=True, null=True, verbose_name='IPO Detail링크'),
        ),
        migrations.AddField(
            model_name='ipo',
            name='ipo_id',
            field=models.IntegerField(default=0, verbose_name='IPO ID'),
        ),
    ]
