# Generated by Django 3.2.3 on 2021-12-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20210705_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipo',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='종료일'),
        ),
        migrations.AddField(
            model_name='ipo',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='시작일'),
        ),
    ]
