# Generated by Django 3.2.3 on 2021-12-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_ipo_stock_brokers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IPOStockBroker',
        ),
    ]
